### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by vstastny** [sectore/purescript-webpack-vanilla-hmr#1]
Hi, could you please described in more detail
- how does it work and what is the benefit comparing to pulp
- how to install  (npm i ?)
- how to use it, specifically in connection with e.g. VS Code or Atom IDE

Thanks

**Comment by sectore** [comment]
@vstastny Please check the [README.md](https://github.com/sectore/purescript-webpack-vanilla-hmr/blob/master/README.md), where you'll find all the answers to you questions. Otherwise feel free to open this issue again ;)
